### ISSUE TITLE
Arguments input probably better to use text area

### ISSUE THREAD

**Issue by gedeh** [rschiefer/MSDeployAllTheThings#1]
Hi Robb,

Your extension is just awesome! I was waiting for https://github.com/Microsoft/vsts-tasks/tree/master/Tasks/IISWebAppDeployment tasks available in TFS 2015 Update 2 but seems it still in preview, so this extension is a life savior! 

Just a suggestion, in _Additional Arguments_ input, you probably want to allow of using text-area as the input. Because sometimes people would like to use a lot of `-setParam`. This probably can be achieved by using:

`"type": "multiLine"`

in inputs section of the /Tasks/MSDeployPackageSync/task.json file. 

Thanks!

**Comment by rschiefer** [comment]
That is a great idea!  

I have updated the field to multiline, tested it and deploy an update to the marketplace.  Enjoy!

Thanks for the feedback.  If you don't mind please make sure to add a review in the marketplace so others know this task is useful.

https://marketplace.visualstudio.com/items?itemName=rschiefer.MSDeployAllTheThings

Thanks again!

**Comment by gedeh** [comment]
Thanks Robb!

Just for clarification, is `-setParam` using newline will work using the new version? For example the content of _Additional Arguments_ is like this:

>-setParam:name='IIS Web Application Name',value='$(WebsiteName)'
>-setParam:kind=TextFile,scope=\\Web.config$,match=\[DB_SERVER\],value='$(DbServer)'

Hendra

**Comment by rschiefer** [comment]
I don't think so. I could potentially strip out new line characters though.  Would that work better for you?

**Comment by gedeh** [comment]
Latest release already works great for me, not a mandatory stuff :) closing this issue. Thanks again!

Also keep an eye on Microsoft's unrelease IIS Web Deploy and Dacpac Deploy tasks. But too bad both of them still in preview, so won't be available in on-premise TFS just yet
