### ISSUE TITLE
pubxml

### ISSUE THREAD

**Issue by rosspi** [rschiefer/MSDeployAllTheThings#3]
Hello,
I assume I can use this extension to publish a package.zip file, however I cannot find any guide anywhere on how to generate a package.zip file!.
I have a .pubxml file ready to go.. how can I turn a build definition in VSO into something that I can publish/send/etc somewhere with this task/extension? thanks.

**Comment by rschiefer** [comment]
You can add the "/t:Package" MSBuild argument to your build step to create a package.

**Comment by Tarig0** [comment]
The canned asp.net build template should work for most webapplication projects.

Website projects are another story
