### ISSUE TITLE
Include the logging from the actual command that runs.

### ISSUE THREAD

**Issue by NoOneAtHome** [rschiefer/MSDeployAllTheThings#7]
The command always reports as successful even if the command fails on the build server.
I use this to deploy to sites deployed internally to our company.  The team that manages our web servers recently changed the port of the destination url we deploy to without communicating to us.  
In release manager MSDeployAllTheThings showed as successfully but the log didn't show what we typically expect.  When I manually ran the command on the build server it errored and was immediately clear what the issue is.  Once I updated the port in the MSDeployAllTheThings task it deployed fine, but having to log on to the build server to troubleshoot is not ideal

**Comment by rschiefer** [comment]
Agreed, not ideal.  I intended (and I thought I coded the task) to output the logs from MSDeploy to the task log.   Will look into this further.  Stay tuned ...

**Comment by rschiefer** [comment]
You are correct it doesn't use the deploy.cmd, instead it calls msdeploy.exe to deploy your package but it does support parameterization.  I added a readme to this repo with links to the VisualStudio.com marketplace and a blog post explaining how to use the task.  

http://www.dotnetcatch.com/2016/03/22/vsts-release-custom-deploy-task-to-deploy-virtual-applications-to-azure/

**Comment by rschiefer** [comment]
Sorry for the delay.  This should not be resolved with the latest version that I just uploaded (0.0.8).
