### ISSUE TITLE
Does this task ignore SetParameters.xml?

### ISSUE THREAD

**Issue by devdigital** [rschiefer/MSDeployAllTheThings#8]
This task doesn't seem to run the `deploy.cmd` batch file, so does it not deal with any environment parameters within the `SetParameters.xml` file?

**Comment by rschiefer** [comment]
You are correct it doesn't use the deploy.cmd, instead it calls msdeploy.exe to deploy your package but it does support parameterization. I added a readme to this repo with links to the VisualStudio.com marketplace and a blog post explaining how to use the task.

http://www.dotnetcatch.com/2016/03/22/vsts-release-custom-deploy-task-to-deploy-virtual-applications-to-azure/

**Comment by devdigital** [comment]
Thanks for the update
