### ISSUE TITLE
MSDeploy failure is not reported back to TFS flow 

### ISSUE THREAD

**Issue by sabbadino** [rschiefer/MSDeployAllTheThings#9]
Hi, I am using the MSDeploy Package Sync. 
It seems that if the call to MSDeploy.exe fails , the powershell script does not return an error to "TFS" .. the task is reported as succesfull, but this is not the case.

**Comment by TRBesser** [comment]
Same here. I ended up having to copy the generated msdeploy command from the logs directly to the cmd window to investigate.

**Comment by rschiefer** [comment]
Sorry for the delay.  This should not be resolved with the latest version that I just uploaded (0.0.8).
